version: '3.1'
services:
  db:
    image: postgres:12-alpine
    container_name: "Delivery"
    ports:
      - '5433:5432'
    volumes:
      - ./pg:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'DeliveryDB'